name: Deploy Backend

on:
  push:
    branches:
      - master # since your repo is on master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 30m
          script: |
            set -e
            echo "Starting deploy"
            whoami

            cd /home/ubuntu/Relay/Backend

            echo "Current directory:"
            pwd

            echo "Listing files:"
            ls -la

            echo "Pulling code..."
            git pull origin master

            echo "Installing deps..."
            npm install
            echo "Running prisma..."
            npx prisma generate || true
            npx prisma migrate deploy || true

            echo "Building..."
            npm run build || true

            echo "PM2 status before:"
            pm2 list

            echo "Restarting app..."
            pm2 reload my-app || pm2 start dist/server.js --name my-app

            echo "PM2 status after:"
            pm2 list

            echo "Deploy done"
